name: ci-build

on:
  push:
    branches: 
      - github-actions
      - master
  pull_request:
    branches:
      - github-actions
      - master
# TODO: Set up caching, clean up file for easier readability 
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
      
      # Dependencies for glfw3
      - name: Install Ubuntu Dependencies
        run: |
         sudo apt update
         sudo apt install -y libxkbcommon-dev libxcursor-dev libgl1-mesa-dev libxrandr-dev libxinerama-dev libxi-dev

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Setup VCPkg
        uses: lukka/run-vcpkg@v11
        with: 
          vcpkgGitCommitId: '74e6536215718009aae747d86d84b78376bf9e09' # 2025.10.17
          vcpkgJsonGlob: ${{ github.workspace }}/vcpkg.json

      - name: Install Packages
        run: |
         vcpkg install --triplet=x64-linux

      - name: Run CMake
        run: |
         mkdir build
         cd build
         cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake .. \
    
        # Must cd into build directory in order to use the Makefile generated by CMake instead of the default Makefile
      - name: Run make
        run: |
         cd build  
         make
      