name: ci-clang-format

on: [push, pull_request]

jobs:
    format-check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: DoozyX/clang-format-lint-action@v0.20
              with: 
                source: '.'
                extensions: 'h, cpp, c'
                clangFormatVersion: 20
                style: file
                # This is the same as the clang-format -i command. Will edit files directly instead of showing the difference.
                inplace: false
                
